package com.github.standobyte.jojo.item;

import com.github.standobyte.jojo.client.render.item.CustomIconItem;

import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;

/**
 * The mod's creative tab.
 *
 * <p>1.16.5 subclassed CreativeModeTab to set the label, the icon and the
 * enchantment categories the tab's search accepted. 1.20.1 builds tabs through
 * CreativeModeTab#builder and takes the supported enchantments from each
 * enchantment's own data (its supported-items tag) instead of a tab-level category
 * list, so the label, the icon and the item list are all that is needed here. The
 * item list is generated by ModItems in the order the items used to declare
 * {@code Item.Properties#tab}, so the tab shows the same items in the same order.</p>
 */
public class ModCreativeTab {

    public static CreativeModeTab create(String label, CreativeModeTab.DisplayItemsGenerator displayItems) {
        return CreativeModeTab.builder()
                .title(Component.translatable("itemGroup." + label))
                .icon(() -> CustomIconItem.makeIconItem(CustomIconItem.CustomModelIcon.MOD_LOGO))
                .displayItems(displayItems)
                .build();
    }
}
